### ISSUE TITLE
url containing brackets in them throws error

### ISSUE THREAD

**Issue by mrkarthik07** [sananth12/ImageScraper#102]
I was trying to download image of particular website something like this http://XYZ.com/XYZ/XYZ.net(3).jpg when i encountered error
bash: syntax error near unexpected token `('

**Comment by ssundarraj** [comment]
Can you try escaping the brackets (i.e. "http://XYZ.com/XYZ/XYZ.net\(3\).jpg")

**Comment by mrkarthik07** [comment]
awesome it works
