### ISSUE TITLE
import image-scraper not working

### ISSUE THREAD

**Issue by VinLark** [sananth12/ImageScraper#103]
I tried making a simple script with image-scraper but it doesn't work. It just makes a new line in the terminal. Am I doing anything wrong or does it just not work? Nothing else is in the script, just 

```
import image_scraper
image_scraper.scrape_images(vinlark.github.io/seinfeld)
```

**Comment by ssundarraj** [comment]
This functionality is no longer supported. It's marked deprecated in the README.
