### ISSUE TITLE
Warning after adding set proc title.

### ISSUE THREAD

**Issue by srirams6** [sananth12/ImageScraper#59]
![screenshot from 2015-04-01 14 15 09](https://cloud.githubusercontent.com/assets/4509724/6937445/9e93a73e-d879-11e4-9cdd-fc2808cd4dd8.png)

**Comment by sananth12** [comment]
@vigneshmanix have a look at this.

**Comment by vigneshmanix** [comment]
It is a bug in setuptools. It was fixed only a few weeks ago. https://bitbucket.org/pypa/setuptools/issue/254/the-default-python-eggs-mode-doesnt
Update setuptools to get rid of the warning.
```sh
pip install setuptools --upgrade
```
Now rebuild the app
```sh
python setup.py install
```
