### ISSUE TITLE
Option for only scraping images with filenames that match a regex

### ISSUE THREAD

**Issue by joshwget** [sananth12/ImageScraper#74]
For example, to only scrape images with filenames that contain a number:

```sh
$ image-scraper --filename-match [0-9] [url to scrape]
```

I'll submit a pull request for this if everyone thinks it would be useful.

**Comment by sananth12** [comment]
@joshwget :+1:  That's a great idea! Will be happy to merge your PR! :smile:

**Comment by srirams6** [comment]
:+1:

**Comment by vigneshmanix** [comment]
:+1:
