### ISSUE TITLE
Python 3 Environment required for development

### ISSUE THREAD

**Issue by suhithr** [sananth12/ImageScraper#90]
Need a python 3 environment to develop, due to many packages having different names in Python 2 and 3. Like the` __builtin__` package. Please update the documentation.

**Comment by ssundarraj** [comment]
@suhithr I didn't quite understand what you meant. Can you please clarify?

**Comment by suhithr** [comment]
Building the file from source with a Python 2 interpreter is not possible, because some packages used only exist in Python 3. For example in progressbar.py the call is `from builtins import range`. To call this package in Python 2 we must call `from __builtin__ import range`. This is because the `__builtin__` module was renamed to `builtins` in Python 3.

**Comment by ssundarraj** [comment]
By build you mean install the package?

**Comment by suhithr** [comment]
Build from source is what I was referring to, such as `python3 setup.py install`. Installing from pip works even without Python 3.

**Comment by ssundarraj** [comment]
It's working for me using Python 2 as well.

**Comment by suhithr** [comment]
Closing because it worked for me as well, I'm not sure if it has anything to do with installing it after installing Python 3
