### ISSUE TITLE
Using image_search in python scripting 

### ISSUE THREAD

**Issue by pybern** [sananth12/ImageScraper#92]
Ok great. So I've downloaded a module called imagescraper from

Pip install ImageScraper 
When running in console

image-scraper 'insert url' 
Works just fine. However following the documentation when I ran in jupyter notebook.

Import image_scraper

image_scraper.search_images('insert url') 
I'm returned a (0, 0) tuple.

I've searched my working directory where my images suppose to be but it's not there.

My curiosity is no longer with scraping images. But I really just wanna work it out and figure why it's no working in my Python book.

**Comment by ssundarraj** [comment]
@n00bc0der, are you able to run it in a python shell?

**Comment by AFAgarap** [comment]
@ssundarraj May I suggest? I think the code

`import image_scraper`
`image_scraper.scrape_images(URL)`

should just be removed from the README.md. So, as to avoid the confusion for the users of your good app. :)

**Comment by ssundarraj** [comment]
@AFAgarap 
We have mentioned that it is deprecated, but I will go ahead and make it more clear. Thanks.

**Comment by sananth12** [comment]
The functionality you are looking for is still available in a previous (deprecated) version.
https://github.com/sananth12/ImageScraper/tree/2.0.6

**Comment by AFAgarap** [comment]
@ssundarraj Yes, thank you as well. :)
