### ISSUE TITLE
Code does not function

### ISSUE THREAD

**Issue by AFAgarap** [sananth12/ImageScraper#94]
I wrote the simple Python script for scraping images. It does not scrape an image at all. Please help? Thank you.

Screenshots
---
![screenshot from 2016-04-05 23 42 43](https://cloud.githubusercontent.com/assets/11130276/14288204/4b1e23ee-fb88-11e5-8431-6feddf1509fe.png)
--
--
![screenshot from 2016-04-05 23 43 03](https://cloud.githubusercontent.com/assets/11130276/14288205/4bae4b5e-fb88-11e5-8b7b-efec47b41379.png)

**Comment by ssundarraj** [comment]
Please check #93

**Comment by AFAgarap** [comment]
So, this means we cannot use ImageScraper in our Python scripts anymore? Aren't there any alternatives? Thank you in advance for your kind response.

**Comment by ssundarraj** [comment]
You can't use it as you have done so at the moment. You can make a call to `image-scraper` though.

**Comment by AFAgarap** [comment]
Oh, yes. Got it. Thank you so much!

**Comment by AFAgarap** [comment]
`import os
os.system('image-scraper <URL>')`

Thank you! :)
