### ISSUE TITLE
Using in script

### ISSUE THREAD

**Issue by ShreeDhamija** [sananth12/ImageScraper#96]
Hey! I'm new to coding so couldn't figure it out but what's the best way to use it in a script? Or run a cron job with it? I basically want to scrape an image everyday and automating the process would be perfect and in the readme it says that the Script process is now deprecated. Any help would be appreciated. Thank you :)

**Comment by sananth12** [comment]
Yep. Cron job will do.

**Comment by AFAgarap** [comment]
@ShreeDhamija May I suggest? I think it is a good idea as well to use the `os` library.

`import os`
`os.system(image-scraper <URL>)`

Just a suggestion :)
