### ISSUE TITLE
image_scraper.scrape_images("http://example.com") does not work for me

### ISSUE THREAD

**Issue by WTRipper** [sananth12/ImageScraper#97]
As written in the title:

import image_scraper
image_scraper.scrape_images("http://example.com")

does not work for me (PyCharm: "Process finished with exit code 0", But nothing happened)
I am using python27 under windows 8.

Using cmd works:
C:\Python27\Scripts>image-scraper http://example.com

**Comment by ssundarraj** [comment]
Please see #92 :)
